language: c

dist: focal

os:

  - linux

env:

  global:

    - pathP="~/build/miscdec/android_kernel_zuk_msm8996"

    - device_model ="zuk_z2row"

    - userdir ="miscdec"

    - compiler=$(if [ -e compiler ];then cat compiler;else echo "notDefine";fi)

    - clang_release=$(if [ "$compiler" = "clang" ];then curl -s https://github.com/kdrag0n/proton-clang/releases/latest | grep -Eo "[0-9]{8}";else echo "notDefine";fi)

before_install:

  # fetch toolchian gcc4.9

  - cd ~/build/$userdir/

  - if [ "$compiler" = "clang" ]; then echo $compiler;wget -c https://github.com/kdrag0n/proton-clang/archive/$clang_release.zip;unzip $clang_release.zip;mv proton-clang-$clang_release clang;export PATH=$PWD/clang/bin:$PATH;export CROSS_COMPILE=aarch64-linux-gnu-;export CROSS_COMPILE_ARM32=arm-linux-gnueabi-;export ARCH=arm64;export SUBARCH=arm64;else echo $compiler; wget -c https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/961622e926a1b21382dba4dd9fe0e5fb3ee5ab7c.tar.gz;mkdir aarch64-linux-android-4.9; tar -zxf 961622e926a1b21382dba4dd9fe0e5fb3ee5ab7c.tar.gz -C aarch64-linux-android-4.9; export PATH=$PWD/aarch64-linux-android-4.9/bin:$PATH; export CROSS_COMPILE=aarch64-linux-android-; export ARCH=arm64; export SUBARCH=arm64; fi

  - whereis clang

  - ${CROSS_COMPILER}ld -v

  - clang --version

stages:

  - name: build kernel

    if: tag IS present

jobs:

  # job parallel

  include:

    - stage: build kernel

      script: 

      - cd $pathP

      - make O=out lcblues-perf_defconfig;

      - if [ "$compiler" = "clang" ]; then echo "use clang to compile";make -j$(nproc --all) CC=clang O=out; else echo "use gcc to compile"; make -j$(nproc --all) O=out; fi

      

      after_success:

        - echo "build finished."

        - curl -s "http://www.pushplus.plus/send" -d "token=$pushplus_taken&title=Successed&content=Tag:${TRAVIS_TAG}"

        - cd ~/build/$userdir/

        - git clone https://github.com/lyq1996/AnyKernel3.git -b master

        - cd AnyKernel3

        - cp $pathP/out/arch/arm64/boot/Image.gz-dtb ./

        - zip -r9 $device_model-Kernel-$TRAVIS_TAG.zip * -x .git README.md *placeholder build.sh *.zip

        - cp $device_model-Kernel-$TRAVIS_TAG.zip $pathP/

        - cd $pathP/

      after_failure:

        - echo "build failed."

        - curl -s "http://www.pushplus.plus/send" -d "token=$pushplus_taken&title=Failed&content=Tag:${TRAVIS_TAG}"

 

      deploy:

        skip_cleanup: true

        provider: releases

        token: $github_oauth_key

        on:

          tags: true

        file: 

          - $device_model-Kernel-$TRAVIS_TAG.zip

      after_deploy:

        - echo "Send notifacation to ServerChan."

        - curl -s "http://www.pushplus.plus/send" -d "token=$pushplus_taken&title=LinkHere&content=https://github.com/$userdir/android_kernel_zuk_msm8996/releases/download/${TRAVIS_TAG}/$device_model-Kernel-${TRAVIS_TAG}.zip"

        

